### ISSUE TITLE
Get-GitStatusPrompt crashes PowerShell on 7.2 preview 8

### ISSUE THREAD

**Issue by ThomasNieto** [felixfbecker/PowerGit#32]
I am unable to capture the exact error message but if you run `Get-GitStatusPrompt` in a git folder it will crash PowerShell.

**Comment by ThomasNieto** [comment]
@felixfbecker do you have any idea what might be causing this crash?

**Comment by felixfbecker** [comment]
According to the release notes, `7.2-preview.8` was upgraded to .NET Core `v6.0.0-preview.6` so LibGit2Sharp will need to be upgraded/compiled against the new version here too.

**Comment by ThomasNieto** [comment]
This is caused by the same issue as described in https://github.com/felixfbecker/PowerGit/issues/35. Closing as a duplicate.
